name: Update Vector DB

on:
  # schedule:
    # 자동으로 매일 자정에 실행하도록 설정 (UTC 시간 기준)
    # - cron: '0 0 * * *'
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      name:
        description: "Deployment?"
        default: "WhaTap"

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scrapy spider
        run: |
          python store.py